const PRODUCT_IMG_INFORMATION = 'productImgDtos';
const PRODUCT_PURITY_INFORMATION = 'productPurityDto';
const PRODUCT_TYPE_INFORMATION = 'productTypeDto';
const PRODUCT_MATERIAL_INFORMATION = 'productMaterialDto';

const ERROR_IMAGE = 'shared/image/ErrorImage.png';
export {PRODUCT_IMG_INFORMATION, PRODUCT_PURITY_INFORMATION,PRODUCT_TYPE_INFORMATION,PRODUCT_MATERIAL_INFORMATION, ERROR_IMAGE};
